version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: anajobs_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: nonprofit_jobs
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - anajobs_network

  anajobs:
    build: .
    container_name: anajobs_app
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      ANAJOBS_MONGODB_URI: mongodb://admin:password@mongodb:27017/nonprofit_jobs?authSource=admin
      ANAJOBS_DATABASE_NAME: nonprofit_jobs
      ANAJOBS_LOG_LEVEL: INFO
    volumes:
      - ./data:/app/data:ro
      - ./logs:/app/logs
      - ./config:/app/config
    networks:
      - anajobs_network
    command: ["python", "-m", "anajobs.cli", "setup"]

  mongo-express:
    image: mongo-express:1.0.0
    container_name: anajobs_mongo_express
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8081:8081"
    networks:
      - anajobs_network

volumes:
  mongodb_data:

networks:
  anajobs_network:
    driver: bridge